---

# http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
aptcachetime: 3600
timezone: "Europe/London"
ssh:
  start: true
  service_enabled: true
  password_auth: false
  root_login: false
  key_pair_path: ~/.ssh/id_rsa
# A list of users who will be added to the docker group.
docker_users: [matthew]
